name: kaida_music
description: A Flutter music app built via Termux + GitHub Actions
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
